### ISSUE TITLE
Missing .bam output file in unstranded paired-end mode

### ISSUE THREAD

**Issue by wenzelm** [cyaguesa/SL-quant#1]
Dear Carlo,

I am evaluating your SL-quant pipeline against my own method (CUTADAPT-based), and I have noticed an error in your script when using unstranded paired-end data.

The script dies in line 173 (specific mode) or 197 (sensitive mode) because both these lines attempt to access the file ${3}_oneEnd_unmapped.bam, which is never generated by the previous block (lines 135-168):
```
if [ "$paired_orientation" == "FR" ]; then
 
      echo "      [1/2] get unmapped R2 reads with mate mapped and convert to fastq"
      samtools view -u -f 133 -F 8 ${2} > ${3}_oneEnd_unmapped.bam        
      echo "      [2/2] get primary alignments of mapped R1 reads with mate unmapped"
      samtools view -u -f 73 -F 260 ${1}  > ${3}_oneEndMapped.bam
      featureCounts_S=2                    # set R1 read orientation for featureCounts (reverse)
      strand="plus"                        # set blast database strandness (normal)
    elif [ "$paired_orientation" == "RF" ]; then
      echo "      [1/2] get R1 reads unmapped with mate mapped and convert to fastq"
      samtools view -f 69 -F 8 ${2} | awk '{OFS="\t"; print ">"$1"\n"$10}' > ${3}_oneEnd_unmapped.fasta
      echo "      [2/2] get primary alignments of R2 reads mapped with mate unmapped"
      samtools view -u -f 137 -F 260 ${1}  > ${3}_oneEndMapped.bam
      featureCounts_S=2                    # set R2 read orientation for featureCounts (reverse)
      strand="minus"                       # set blast database strandness (reverse)
    else
      echo "      [1/2] get reads unmapped with mate mapped and convert to fastq"
      samtools view -f 5 -F 8 ${2} | awk '{OFS="\t"; print ">"$1"\n"$10}' > ${3}_oneEnd_unmapped.fasta
      echo "      [2/2] get reads mapped with mate unmapped"
      samtools view -u -f 9 -F 260 ${1}  > ${3}_oneEndMapped.bam
      featureCounts_S=0                   # set read orientation for featureCounts (unstranded)
      strand="both"                       # set blast database strandness (unstranded)
    fi
```

It looks like this BAM file is only generated for FR strandedness, but RF or unstranded immediately convert to FASTA instead.

I've edited the script to save the BAM file before converting to FASTA, and it looks like the rest of the script is now running fine. Is this a bug or have I configured the pipeline wrong for my data?

Thanks and best wishes,
Marius

**Comment by cyaguesa** [comment]
Hi Marius,
Thank you for your thorough report. This indeed appears to be a bug due to a previous script update that I failed to apply to the multiple orientation cases. The workaround you propose is correct, and I have now corrected the script accordingly.
Sorry for the late answer and please let me known if you find other issues.

**Comment by cyaguesa** [comment]
PS: I really like how fast, efficient, and simple your CUTADAPT-based method is. If I had read about it before, I might not have had to develop the BLAST-based method ! In any case, your method became an important part of this project. Thank you for it ! Again, let me known if you find other issues.
Carlo
